# Password is required 
requirepass 7aStgp6OCwAHTNXBp1MGRxh0XgXFjoFcQZDSeVG5KKs=

# Network bindings Configuration
port 6379
protected-mode no

# Core Storage Parameters (Updated to Linux directory patterns)
dir /data
dbfilename dump.rdb

# Persistence Layer Configuration
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# Snapshot Recovery Milestones
save 3600 1 300 100 60 10000
stop-writes-on-bgsave-error no

# Diagnostic Tools
enable-debug-command yes

# System Logging (Routed to standard /data storage or console stdout)
logfile "/data/redis.log"
loglevel notice
